# Generated by Django 2.2.4 on 2019-09-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_auto_20190905_0151'),
        ('registro_hora_extra', '0002_auto_20190905_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionario.Funcionario'),
            preserve_default=False,
        ),
    ]
