# Generated by Django 2.2.4 on 2019-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0005_auto_20190912_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='utilizida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
