# Generated by Django 2.2.4 on 2019-10-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0006_auto_20191003_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohoraextra',
            old_name='utilizida',
            new_name='utilizada',
        ),
    ]
